
export const metadata: Metadata = {
  description: "Generated by create next app",

export default function RootLayout({
  children,
}: Readonly<{
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
