import type { Metadata } from "next"
import "./globals.css"
import { ClerkProvider } from "@clerk/nextjs"
import { Navbar } from "@/components/custom/Navbar"

export const metadata: Metadata = {
  title: "BookIt",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <Navbar />
      <html lang="en">
        <body
          // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
          className={`antialiased`}
        >
          {children}
        </body>
      </html>
    </ClerkProvider>
  )
}
